### ISSUE TITLE
Broken DM composer text box - only takes up half of it's container

### ISSUE THREAD

**Issue by JulienMelissas** [jxnblk/Twipster#51]
See here:
![screenshot 2015-05-06 16 55 30](https://cloud.githubusercontent.com/assets/2278221/7503467/351f05c4-f411-11e4-8822-688054469e66.png)

I think this can be fixed by adding just a tad bid of CSS:

```
.DMConversation-composer {
  width: 100%;
}
```

Seems to have fixed it:
![screenshot 2015-05-06 17 00 34](https://cloud.githubusercontent.com/assets/2278221/7503501/73d05fa2-f411-11e4-9e71-36f236594d4b.png)

Let me know if you'd like me to submit a PR, happy to do it.

**Comment by JulienMelissas** [comment]
Also @acodesmith thanks for being featured here. Now everyone knows we like to get :beers:

**Comment by dep** [comment]
This seems to no longer be an issue, Screenshot: http://dl.dpeck.net/eQYCVS

![](http://dl.dpeck.net/eQYCVS+)
